@host=http://localhost:3000
###

# @name Posts
GET {{host}}/trips HTTP/1.1

###

# @name FetchPostByID
GET {{host}}/trips/6 HTTP/1.1

###

# @name NewPost
POST {{host}}/trips HTTP/1.1
content-type: application/json

{
  "country": "França",
  "place": "Paris",
  "flagUrl": "https://en.wikipedia.org/wiki/Flag_of_France#/media/File:Flag_of_France.svg",
  "goal": "2014-10",
  "createdAt": "2022-04",
  "updatedAt": "2022-06"
}
###

# @name UpdatePost
PATCH {{host}}/trips/10 HTTP/1.1
content-type: application/json

{
  "place": "Catuji",
  "goal": "2023-02"
}
###

# @name DeletePost
DELETE {{host}}/trips/9 HTTP/1.1
content-type: application/json

###